// Shared types between frontend and backend

export interface Tag {
    name: string;
    category: 'Language' | 'Framework' | 'Concept' | 'Task' | 'Other';
}

export interface LogEntry {
    id: string;
    content: string;
    timestamp: number;
    tags: Tag[];
    source: 'manual' | 'github' | 'voice';
    summary?: string;
    needsAiProcessing?: boolean;
    processedForSkillTree?: boolean;
}

export interface DailySummary {
    date: string; // YYYY-MM-DD
    content: string;
    keyAchievements: string[];
    techStackUsed: string[];
    autoGenerated?: boolean;
    processedForSkillTree?: boolean;
}

export interface Skill {
    id: string;
    category: 'Language' | 'Framework' | 'Tool' | 'Concept' | 'Platform';
    name: string;
    maturityLevel: number; // 1-5
    workExamples: string[];
    relatedLogs: string[];
    firstSeen: Date;
    lastUpdated: Date;
}

export interface BlogPost {
    id: string;
    title: string;
    content: string; // Markdown
    dateRange: { start: number; end: number };
    createdAt: number;
}
