import { sqliteTable, text, integer, blob } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// Logs table - main entries
export const logs = sqliteTable('logs', {
    id: text('id').primaryKey(),
    content: text('content').notNull(),
    timestamp: integer('timestamp').notNull(),
    tagsJson: text('tags_json').default('[]'),
    source: text('source').notNull().default('manual'),
    summary: text('summary'),
    needsAiProcessing: integer('needs_ai_processing', { mode: 'boolean' }).default(false),
    processedForSkillTree: integer('processed_for_skill_tree', { mode: 'boolean' }).default(false),
    createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
});

// Daily summaries table
export const dailySummaries = sqliteTable('daily_summaries', {
    date: text('date').primaryKey(), // YYYY-MM-DD
    content: text('content').notNull(),
    keyAchievementsJson: text('key_achievements_json').default('[]'),
    techStackJson: text('tech_stack_json').default('[]'),
    autoGenerated: integer('auto_generated', { mode: 'boolean' }).default(false),
    processedForSkillTree: integer('processed_for_skill_tree', { mode: 'boolean' }).default(false),
    createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
});

// Skill tree table
export const skillTree = sqliteTable('skill_tree', {
    id: text('id').primaryKey(),
    category: text('category').notNull(), // Language, Framework, Tool, Concept, Platform
    name: text('name').notNull(),
    maturityLevel: integer('maturity_level').notNull().default(1), // 1-5
    workExamplesJson: text('work_examples_json').default('[]'),
    relatedLogsJson: text('related_logs_json').default('[]'),
    firstSeen: integer('first_seen', { mode: 'timestamp' }).default(sql`(unixepoch())`),
    lastUpdated: integer('last_updated', { mode: 'timestamp' }).default(sql`(unixepoch())`),
});

// Processing queue for batch AI operations
export const processingQueue = sqliteTable('processing_queue', {
    id: text('id').primaryKey(),
    type: text('type').notNull(), // 'tag_extraction', 'skill_tree_update', 'daily_recap'
    referenceId: text('reference_id'),
    status: text('status').notNull().default('pending'), // pending, processing, completed, failed
    createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
    processedAt: integer('processed_at', { mode: 'timestamp' }),
});

// Blog posts table
export const blogPosts = sqliteTable('blog_posts', {
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    dateRangeStart: integer('date_range_start').notNull(),
    dateRangeEnd: integer('date_range_end').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
});

// App state table for storing miscellaneous state
export const appState = sqliteTable('app_state', {
    key: text('key').primaryKey(),
    value: text('value'),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`(unixepoch())`),
});

// Type exports for use in the application
export type Log = typeof logs.$inferSelect;
export type NewLog = typeof logs.$inferInsert;
export type DailySummary = typeof dailySummaries.$inferSelect;
export type NewDailySummary = typeof dailySummaries.$inferInsert;
export type Skill = typeof skillTree.$inferSelect;
export type NewSkill = typeof skillTree.$inferInsert;
export type BlogPost = typeof blogPosts.$inferSelect;
export type NewBlogPost = typeof blogPosts.$inferInsert;
